version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: plena-mongo
    ports:
      - '27017:27017'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
